module.exports = {
  DISCORD_TOKEN: 'redacted',
  NOW_LIVE_CHANNEL_ID: 'NO LONGER USED',
  TWITTER_CONSUMER_KEY: 'NO LONGER USED',
  TWITTER_CONSUMER_SECRET: 'NO LONGER USED',
  TWITTER_TOKEN_KEY: 'NO LONGER USED',
  TWITTER_TOKEN_SECRET: 'NO LONGER USED',
  SELFIE_CHANNEL_ID: 'redacted'
}
